### ISSUE TITLE
hard to setup for a simple "test-environment"

### ISSUE THREAD

**Issue by individual-it** [eneiluj/integration_openproject#9]
connecting this app to a simple OpenProject test-environment / development environment running e.g. under `http://localhost:3000` is prevented by:
1. replacing the openproject URL to have `https` as protocol
2. checking the openproject URL to have at least one dot in the domain name regex: `'/^(https?:\/\/)?[^.]+\.[^.].*/'`
3. NC not accepting `localhost` as "remote server" - this is easily solvable by setting a system setting `./occ config:system:set allow_local_remote_servers --value 1`

would you be happy for me to do a PR changing 1. and 2. ? 

For 1. we could have a warning saying it is not "secure" using "HTTP"
For 2. I think a domain name without a `.` should be just accepted because its perfectly valid

**Comment by individual-it** [comment]
using HTTPS on localhost e.g. as explained in
https://github.com/opf/openproject/blob/dev/docs/development/localhost-ssl/README.md
has the problem that curl does not accept self signed certificates by default, looking into if there is an option to allow that in NC

**Comment by individual-it** [comment]
NC has its own certbundle in `resources/config/ca-bundle.crt` so the certificate created for OpenProject can be simply added there, that makes this app work without any code changes on a local installation with HTTPS

**Comment by eneiluj** [comment]
I totally agree :grin:.

1. This is now done differently. "https://" is now prepended on save (instead of on input) only if there is no protocol.
2. The new regex is `/^https?:\/\/[^ "]+$/`
3. You're right, setting this config setting will let NC server make requests to localhost.

Feel free to directly create a PR for changes you consider relevant.

**Comment by individual-it** [comment]
@eneiluj thank you. I've done similar fixes for the PHP code in #10 because even the frontend would accept `localhost` as url, the PHP code would refuse it
